{'src/mod_websocket', [{outdir, "ebin"}, {i, "../ejabberd/src"}]}.
{'src/ejabberd_xmpp_websocket', [{outdir, "ebin"}, {i, "../ejabberd/src"}]}.
{'src/ejabberd_websocket', [{outdir, "ebin"}, {i, "../ejabberd/src"}]}.
